package types

var RegionNamingMap = map[string]string{
	"piemonte":            "Piemonte",
	"veneto":              "Veneto",
	"lombardia":           "Lombardia",
	"emiliaromagna":       "Emilia Romagna",
	"umbria":              "Umbria",
	"lazio":               "Lazio",
	"toscana":             "Toscana",
	"abruzzo":             "Abruzzo",
	"molise":              "Molise",
	"basilicata":          "Basilicata",
	"puglia":              "Puglia",
	"marche":              "Marche",
	"sicilia":             "Sicilia",
	"sardegna":            "Sardegna",
	"liguria":             "Liguria",
	"trento":              "Provincia autonoma di Trento",
	"bolzano":             "Provincia Autonoma di Bolzano",
	"friuliveneziagiulia": "Friuli Venezia Giulia",
	"valledaosta":         "Valle d'Aosta",
	"campania":            "Campania",
	"calabria":            "Calabria",
}
