name: Autoupdate

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.6"
      - name: run
        run: |
          go run main.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update(data.json): automatic update"
          file_pattern: "data.json"
